Runnable/ponos

- README.md
> Consistant Badges

- README.md
I'm _so good_ at fixing things the first time...
> Fix David Dependencies Badge

- lib/server.js
- package.json
- test/unit/server.js
Updating runnable-hermes to ~~6.0.0~~ ~~6.1.0~~ 6.2.1 and updating various things that changed in that module.
> runnable-hermes@6.2.1 Update

- lib/server.js
- package.json
- test/functional/basic.js
- test/functional/failing.js
- test/functional/timeout.js
- test/unit/server.js
They were initially implemented as promise methods, but they do not perform any async operations.
> Changed `setTask` and `setAllTasks` to be synchronous.

- .npmignore
- package.json
- resources/mocha-bootstrap.js
- test/functional/failing.js
- test/functional/timeout.js
- test/unit/errors/task-error.js
- test/unit/errors/task-fatal-error.js
- test/unit/logger.js
- test/unit/server.js
- test/unit/worker.js
Adding a mocha bootstrap to catch any promises that are not handled.
> Mocha Bootstrap

- lib/server.js
- lib/worker.js
- package.json
- test/functional/timeout.js
Updated the following dependencies:
- bluebird@3.0.5
Updated the following dev-dependencies:
- istanbul@0.4.0
Removed the following dependencies:
- loadenv (wasn't actually being used for anything)
> Updated Bluebird, Istanbul

- lib/server.js
- test/unit/server.js
useful for using ponos in api side-by-side w/ existing workers
> unsubscribe and unsubscribeAll

- lib/server.js
- package.json
- test/unit/server.js
Have to start naming the Ponos server. Hermes got updated with a breaking change on a minor update, so we have to fix this asap.
> Hermes Update

- .gitignore
- .travis.yml
- README.md
- lib/errors/task-error.js
- lib/logger.js
- lib/server.js
- lib/worker.js
- package.json
- resources/generate-docs.sh
- test/unit/errors/task-error.js
- test/unit/errors/task-fatal-error.js
- test/unit/logger.js
- test/unit/server.js
- test/unit/worker.js
Various updates.
- add documentation generator w/ `jsdoc`
- add documentation generation script w/ upload to GitHub Pages
- clean up formatting in code/tests
- clean up docs
- add link to documentation in README
> Maintenance Update

- lib/server.js
- test/unit/server.js
> Change throw to warn log on queue checks

- .travis.yml
put language in the allowed failures so it'll actually work on travis. :)
> fix allowed failures entry

- .travis.yml
it did bad things when we did this. 1.3.0 was botched in npm's servers. I unpublished 1.3.0 and published 1.3.1 which didn't add too much at all.
> remove npm publish

- .travis.yml
it'll only deploy tags and only on node 4
> auto deploy to NPM

- README.md
> Travis Badge: use master

- .travis.yml
- package.json
report coverage information to codeclimate
> codeclimate: report coverage

- src/rabbitmq.js
- src/server.js
- src/worker.js
Adding types to all the Promises and adding a few missing types.
> strengthening types

- src/rabbitmq.js
Fixing the JSdocs to reflect that.
> _validatePublish is a private function

- interfaces/modules/bunyan.js.flow
- src/logger.js
- src/server.js
- src/worker.js
- test/unit/logger.js
huzzah! more types, the better!
> fixing types; adding bunyan types

- src/rabbitmq.js
- src/worker.js
- test/unit/worker.js
* allow log to be passed for rabbit model
* update joi def for schema
> allow log to be passed for rabbit. update joi def

- src/worker.js
- test/unit/worker.js
> revert change, as joi does not work for some reason

- .flowconfig
- interfaces/modules/101.js.flow
- src/rabbitmq.js
- test/unit/rabbitmq.js
* if jobSchema passed, validate before publish
* add TID to validation
> add validation for publish

- src/server.js
- src/worker.js
- test/functional/failing.js
- test/functional/fixtures/worker.js
- test/functional/retry-limit.js
- test/functional/tid.js
- test/functional/timeout.js
- test/unit/server.js
- test/unit/worker.js
* break out run into smaller tasks
> San 4875 refactor methods

- src/rate-limiters/redis.js
- src/worker.js
- test/unit/worker.js
> pick opts fields

- src/rabbitmq.js
- test/unit/rabbitmq.js
Track how many jobs are published and what app published them
> Implement publishing monitor

- src/rabbitmq.js
- src/server.js
- src/worker.js
- test/functional/basic.js
- test/functional/fixtures/worker.js
- test/functional/retry-limit.js
- test/unit/rabbitmq.js
- test/unit/server.js
- test/unit/worker.js
Added `timestamp` to the message properties. 
Pass job properties/metadata along the `job` payload into the task handler. Optional to use
> Add timestamp

- src/rabbitmq.js
- test/unit/rabbitmq.js
In order to set, for example, expiration or delivery mode.
> Add options to publish* methods

- src/rabbitmq.js
- src/server.js
Adding missing logs and expanding existing ones.
> Add more logs
