lib/logger.js
In the logs, I was seeing `err: {}` for logged errors. Turns out that bunyan needs the stdSerializers in its instance to be able to print them correctly
=> bunyan standard serializers

README.md, lib/worker.js, test/functional/fixtures/timeout-worker.js, test/functional/timeout.js, test/unit/worker.js
Now workers can be set to time out! Pretty cool, eh!? Unit and functional tests have been created for this functionality.
~~One interesting corner is that setting the timeout to 0 does not actually give the worker infinite time (it will fail almost immediately). Is this good? Is that what we want to do? I might be able to have the timeout added conditionally, but I just want to pose the question.~~
Edit: I think the `0` timeout thing has been resolved. See discussion below.
=> worker timeouts

lib/worker.js, test/unit/worker.js
The worker class was ignoring the `log` and `errorCat` options it was being passed. Fixed this.
=> Fix Worker Options

lib/server.js, test/unit/server.js
Ponos currently throws an error if not all queues listed in hermes have associated workers.
This PR replaces the throw with a warn log.
=> Replace throw with warn log

.travis.yml
added a deploy section to `.travis.yml` to get it to deploy to NPM for us. pretty sweet.
the API token in here is encrpyted and should only be able to be read by travis.
=> use travis to deploy to npm

lib/worker.js, package.json, test/unit/worker.js
Add counter and timer for all ponos jobs. Hidden behind flag.
- increment for all started jobs
- increment for all jobs results: success, timeout error, fatal error, task error
- ponos.timer to track how long each task execution took
Tasks:
=> Add monitor-dog

package.json
Specifying the node engine with which this package will work. Since it needs node 4, this is a good thing. Since we're not testing against node 5 and guaranteeing support, I exclude it here.
[docs on engines](https://docs.npmjs.com/files/package.json#engines)
=> package.json engine

src/rabbitmq.js, test/unit/rabbitmq.js
as the title says - if we clear these, we can reconnect the model, which is useful. it will lose all it's subscriptions, but I think that's okay. this is mostly for testing purposes anyway for other projects when they want to use the rabbitmq model
fixes #39
=> clear channel and connection on disconnect

src/rabbitmq.js, src/server.js, test/unit/rabbitmq.js, test/unit/server.js
Let's add the ability to namespace the queues we create to connect to fanout exchanges. That would be great, no?
Fixes #37
=> Name RabbitMQ Client & Queues

interfaces/modules/amqplib.js.flow, interfaces/modules/bluebird.js.flow, src/rabbitmq.js, src/server.js, test/functional/basic.js, test/functional/failing.js, test/functional/timeout.js, test/unit/rabbitmq.js
Adds two methods to the RabbitMQ model:
- `publishToQueue(queue, content)`
- `publishToExchange(exchange, routingKey, content)`
Made the model public in the documentation and exposed only the above two methods and `connect` and `disconnect` in the documentation.
Updated the examples and tests accordingly.
Fixes #38
=> Publish methods

interfaces/modules/amqplib.js.flow, src/rabbitmq.js, test/unit/rabbitmq.js
In order to make the `.publishTo*` methods ensure they _actually_ publish when they resolve, I have to use a "confirm queue" through `amqplib` to make sure that things are confirmed when published. Requires setting up a second channel (which was a thought originally anyway), but does make for better reliability when publishing messages.
=> Confirm Publish

src/rabbitmq.js, test/functional/basic.js, test/functional/failing.js, test/functional/timeout.js, test/unit/rabbitmq.js
The following methods have been added. the `publishTo*` methods have been deprecated and will be removed in a later release.
- `publishToQueue(queue, job)` has been replaced with `publishTask(queue, job)`
- `publishToExchange(exchange, routingKey, job)` has been replaced with `publishEvent(exchange, job)` (and assumes a routing key of `''`)
I did _not_ leave backwards support for these functions, though I suppose I could adjust this a bit and do that easily.
=> make publish methods more clear

.codeclimate.yml
don't need codeclimate to be judging these folders.
=> codeclimate: ignore supporting folders

interfaces/modules/joi.js.flow, package.json, src/server.js, src/worker.js, test/functional/retry-limit.js, test/unit/server.js, test/unit/worker.js
We realised we need a way to task fatal item in our queues so that we do not continuously kill our system. We also wanted hook so that we can write to a database in case of a service outage.
* added max retry param per job
* added max retry function to run after limit was reached
* added joi for input validation
* added flow type for joi
* updated test
* added new test
=> add param to set max retry limit and a recovery function.

src/worker.js, test/unit/worker.js
For each job it's possible to optionally specify joi `jobSchema`. Before running task we would validate job against schema and fail with `WorkerStopError` if needed.
=> Add optional job validation

interfaces/modules/joi.js.flow, src/rabbitmq.js, test/functional/basic.js, test/functional/failing.js, test/functional/retry-limit.js, test/functional/tid.js, test/functional/timeout.js, test/unit/rabbitmq.js, test/unit/worker.js
* make publisher assert queue for tasks (subscribers should not know about publishers, it couples them)
* remove asserting task queue from subscribers
* make publisher assert exchange (publisher should setup its exchange, not subscriber)
* make event subscriber assert its queue to the exchange (publisher should not setup subscribers queue)
* update flow definitions
* add app name to tasks
* add joi schemas for tasks and queues
=> add assert to publishers

src/worker.js
Sometimes we pass references to file as job definition. If the file has private functions (other than `task`) it will throw a validation error.
This PR fixes that.
=> Make opts schema flexible

interfaces/modules/amqplib.js.flow, src/rabbitmq.js, src/server.js, test/unit/rabbitmq.js, test/unit/server.js
Add headers to the jobs. Right now there is only one default header: 'publisher'. It shows who created job originally. Useful for debugging.
Also changed log levels in few places from trace to info.
=> Add metadata

src/rabbitmq.js, src/rate-limiters/redis.js, test/unit/rabbitmq.js
Fix #91
This seems to be correct way to set publisher.
We could use headers, but it seems like `appId` is just for that
=> Rename headers.publisher to appId

src/rabbitmq.js, src/worker.js, test/functional/basic.js, test/functional/fixtures/worker-one.js, test/functional/fixtures/worker-tid.js, test/functional/fixtures/worker-two.js, test/functional/fixtures/worker.js, test/unit/rabbitmq.js
`jobMeta` now has `headers.previousEvent` with name of the event that triggered current event.
=> Track origin event

package.json, src/server.js, src/worker.js, test/functional/fixtures/worker-one.js, test/functional/fixtures/worker-two.js, test/unit/server.js, test/unit/worker.js
Add `errorPublisher` that would publish all worker stop errors to the global `error` exchange
=> Add global error events

src/worker.js
* add data to error right before we publish
=> move this._addWorkerDataToError to before rollbar reporting

package.json, src/server.js, test/unit/server.js
We we subscribe to exchange and create queues there is no way to pass queueOptions right now.
So we can't say `autoDelete: true` or something like that.
This PR fixes this problem.
=> Add ability to pass queueOptions to queues create on the subscribed exchange
